# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "kalilinux/rolling"

  # Upload the provisioner script to the guest machine
  config.vm.provision "file", 
    source: "provisioner/kali.sh", 
    destination: "/tmp/provisioner.sh"

  # Execute the provisioner script
  config.vm.provision "shell",
    inline: "sudo /bin/bash /tmp/provisioner.sh"

  # Reboot the box after provisioning
  config.vm.provision :reload
  
	config.vm.provider "vmware_desktop" do |v|
		# Display the VMware GUI when booting the machine
		v.gui = true

    # Set to stop error message from displaying
    v.allowlist_verified = true

		# Customize the amount of memory on the VM:
		v.vmx["memsize"] = "4096"
		
		# Customize the number of CPUs
		v.vmx["numvcpus"] = "2"
		
		# Set provider name
		v.vmx["displayName"] = "kali"

    # Add USB Device
    v.vmx["usb"] = true
    v.vmx["usb.present"] = true

    # Enable USB 3.1
    v.vmx["usb_xhci.present"] = true

    # Enable Shared Bluetooth
    v.vmx["usb.vbluetooth.startConnected"] = true
    v.vmx["ehci.present"] = true

    # Add a Sound Card
    v.vmx["sound"] = true
    v.vmx["sound.autoDetect"] = true
    v.vmx["sound.present"] = true
    v.vmx["sound.startconnected"] = true
	end
end
